[package]
name = "wakformat"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-map = "3.1.0"
zerocopy = "0.9.0-alpha.0"
colored = "3.1.1"
bzip2 = { version = "0.6.1", optional = true }
tar = { version = "0.4.46", default-features = false, optional = true }
fastrand = { version = "2.5.0", optional = true }

bulletformat = { version = "1.8.0", optional = true }

[features]
default = ["cli"]
cli = ["dep:bzip2", "dep:tar", "dep:fastrand"]

[[bin]]
name = "wakformat"
path = "tools/main.rs"
required-features = ["cli"]

[profile.release]
lto = "thin"
codegen-units = 1
